### ISSUE TITLE
pastebin link expired for landroid-cloud.js

### ISSUE THREAD

**Issue by MagnusKlingenberg** [mjiderhamn/worx-landroid-nodejs#22]
The pastebin link used to get the guest token is no longer available making login fail.
Should we add the guest token into the code/config or was there a point to having it external?

**Comment by Bouni** [comment]
Maybe the token was fetched from an external source in order to circumvent possible legal issues in some countries where reverse engineering is considered illegal.
I'm not sure if that's a real problem, I've found out that the token is the same for every user of the app.
If you download the APK from the play store and decompile it, you'll find the same token.
